server:
  port: 8083

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: sa
    url: jdbc:h2:mem:keycloakdb1

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: ravaneswaran
      password: welcome
    realmImportFile: mnr-chinnasamy-realm.json