server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:~/.h2-database:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: ravaneswaran
      password: welcome
    realmImportFile: mnr-chinnasamy-realm.json